#!/bin/bash

# Activate the swap memory
sudo swapon /dev/mmcblk1p2

# Install the trained data for each language of tesseract ocr
sudo apt-get install tesseract-ocr-afr
sudo apt-get install tesseract-ocr-amh
sudo apt-get install tesseract-ocr-ara
sudo apt-get install tesseract-ocr-asm
sudo apt-get install tesseract-ocr-aze
sudo apt-get install tesseract-ocr-aze_cyrl
sudo apt-get install tesseract-ocr-bel
sudo apt-get install tesseract-ocr-ben
sudo apt-get install tesseract-ocr-bod
sudo apt-get install tesseract-ocr-bos
sudo apt-get install tesseract-ocr-bul
sudo apt-get install tesseract-ocr-cat
sudo apt-get install tesseract-ocr-ceb
sudo apt-get install tesseract-ocr-ces
sudo apt-get install tesseract-ocr-chi_sim
sudo apt-get install tesseract-ocr-chi_tra
sudo apt-get install tesseract-ocr-chr
sudo apt-get install tesseract-ocr-cym
sudo apt-get install tesseract-ocr-dan
sudo apt-get install tesseract-ocr-deu
sudo apt-get install tesseract-ocr-dzo
sudo apt-get install tesseract-ocr-ell
sudo apt-get install tesseract-ocr-eng
sudo apt-get install tesseract-ocr-enm
sudo apt-get install tesseract-ocr-epo
sudo apt-get install tesseract-ocr-est
sudo apt-get install tesseract-ocr-eus
sudo apt-get install tesseract-ocr-fas
sudo apt-get install tesseract-ocr-fin
sudo apt-get install tesseract-ocr-fra
sudo apt-get install tesseract-ocr-frk
sudo apt-get install tesseract-ocr-frm
sudo apt-get install tesseract-ocr-gle
sudo apt-get install tesseract-ocr-glg
sudo apt-get install tesseract-ocr-grc
sudo apt-get install tesseract-ocr-guj
sudo apt-get install tesseract-ocr-hat
sudo apt-get install tesseract-ocr-heb
sudo apt-get install tesseract-ocr-hin
sudo apt-get install tesseract-ocr-hrv
sudo apt-get install tesseract-ocr-hun
sudo apt-get install tesseract-ocr-iku
sudo apt-get install tesseract-ocr-ind
sudo apt-get install tesseract-ocr-isl
sudo apt-get install tesseract-ocr-ita
sudo apt-get install tesseract-ocr-ita_old
sudo apt-get install tesseract-ocr-jav
sudo apt-get install tesseract-ocr-jpn
sudo apt-get install tesseract-ocr-kan
sudo apt-get install tesseract-ocr-kat
sudo apt-get install tesseract-ocr-kat_old
sudo apt-get install tesseract-ocr-kaz
sudo apt-get install tesseract-ocr-khm
sudo apt-get install tesseract-ocr-kir
sudo apt-get install tesseract-ocr-kor
sudo apt-get install tesseract-ocr-kur
sudo apt-get install tesseract-ocr-lao
sudo apt-get install tesseract-ocr-lat
sudo apt-get install tesseract-ocr-lav
sudo apt-get install tesseract-ocr-lit
sudo apt-get install tesseract-ocr-mal
sudo apt-get install tesseract-ocr-mar
sudo apt-get install tesseract-ocr-mkd
sudo apt-get install tesseract-ocr-mlt
sudo apt-get install tesseract-ocr-msa
sudo apt-get install tesseract-ocr-mya
sudo apt-get install tesseract-ocr-nep
sudo apt-get install tesseract-ocr-nld
sudo apt-get install tesseract-ocr-nor
sudo apt-get install tesseract-ocr-ori
sudo apt-get install tesseract-ocr-pan
sudo apt-get install tesseract-ocr-pol
sudo apt-get install tesseract-ocr-por
sudo apt-get install tesseract-ocr-pus
sudo apt-get install tesseract-ocr-ron
sudo apt-get install tesseract-ocr-rus
sudo apt-get install tesseract-ocr-san
sudo apt-get install tesseract-ocr-sin
sudo apt-get install tesseract-ocr-slk
sudo apt-get install tesseract-ocr-slv
sudo apt-get install tesseract-ocr-spa
sudo apt-get install tesseract-ocr-spa_old
sudo apt-get install tesseract-ocr-sqi
sudo apt-get install tesseract-ocr-srp
sudo apt-get install tesseract-ocr-srp_latn
sudo apt-get install tesseract-ocr-swa
sudo apt-get install tesseract-ocr-swe
sudo apt-get install tesseract-ocr-syr
sudo apt-get install tesseract-ocr-tam
sudo apt-get install tesseract-ocr-tel
sudo apt-get install tesseract-ocr-tgk
sudo apt-get install tesseract-ocr-tgl
sudo apt-get install tesseract-ocr-tha
sudo apt-get install tesseract-ocr-tir
sudo apt-get install tesseract-ocr-tur
sudo apt-get install tesseract-ocr-uig
sudo apt-get install tesseract-ocr-ukr
sudo apt-get install tesseract-ocr-urd
sudo apt-get install tesseract-ocr-uzb
sudo apt-get install tesseract-ocr-uzb_cyrl
sudo apt-get install tesseract-ocr-vie
sudo apt-get install tesseract-ocr-yid
